# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37421706a7d2c92c3ea5fb9dd2410d57a01fdbdffb6d36c37db96445f546f088ef71e42d3a83831e3a563fcdc64f4959de9ee290670fc364ddcd72e3cb1a6f37

test:
  secret_key_base: 6db6163a1c0a0ca3386d11157f85ddc0c87e6887d50eed13b6da77d719427b4338460fe6e8510e3b64e796a1f7bb97abbe4952e5306b4efd99d6df8e50b566aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
